FROM alpine:3.5

# Custom helper scripts to download PHP and manage PHP extensions
COPY download-php install-php-ext /usr/local/bin/

ENV PHP_INI_DIR /usr/local/etc/php
ENV PHP_CFLAGS="-fstack-protector-strong -fpic -fpie -O2"
ENV PHP_CPPFLAGS="$PHP_CFLAGS"
ENV PHP_LDFLAGS="-Wl,-O1 -Wl,--hash-style=both -pie"

# Persistent runtime dependencies
ENV PHP_DEPS \
        libedit \
        zip \
        unzip \
        git \
        icu \
        gettext \
        libxslt \
        libjpeg-turbo \
        freetype \
        libxml2 \
        curl \
        nginx \
        nginx-mod-http-headers-more \
        bash \
        runit

# PHP build dependencies which get removed
ENV BUILD_DEPS \
        autoconf \
        file \
        g++ \
        gcc \
        make \
        automake \
        libtool \
        bison \
        re2c \
        pkgconf \
        libc-dev \
        libedit-dev \
        curl-dev \
        freetype-dev \
        gd-dev \
        bzip2-dev \
        fcgi-dev \
        krb5-dev \
        libpq \
        icu-dev \
        gettext-dev \
        pcre-dev \
        expat-dev \
        zlib-dev \
        libpng-dev \
        libxslt-dev \
        libxml2-dev \
        libjpeg-turbo-dev \
        gnupg

RUN set -x \
	  && addgroup -g 82 -S www-data \
	  && adduser -u 82 -D -S -G www-data www-data \
    && apk add --no-cache ca-certificates openssl \
    # PHP
    && apk add --no-cache --virtual .build-deps $BUILD_DEPS \
    && apk add --no-cache $PHP_DEPS \
    && mkdir -p $PHP_INI_DIR/conf.d /usr/src \
    && cd /usr/src \
    && download-php \
    && cd php-* \
    && export CFLAGS="$PHP_CFLAGS" \
              CPPFLAGS="$PHP_CPPFLAGS" \
              LDFLAGS="$PHP_LDFLAGS" \
    && ./configure \
        # Core configure options
        --with-libdir=/lib/x86_64-linux-gnu \
        --disable-rpath \
        # Bundled PHP extensions
        --enable-bcmath \
        --enable-calendar \
        --enable-mbstring \
        --enable-exif \
        --enable-ftp \
        --with-gd \
        --enable-gd-native-ttf \
        --with-jpeg-dir=/usr \
        --with-png-dir=/usr \
        --with-freetype-dir \
        --enable-intl \
        --with-pcre-regex \
        --enable-mysqlnd \
        --with-openssl \
        --with-xsl \
        --enable-zip \
        --enable-sysvsem \
        --enable-sysvshm \
        --enable-sysvmsg \
        --enable-shmop \
        --enable-sockets \
        --with-zlib \
        --with-zlib-dir \
        --with-bz2 \
        --with-curl \
        --with-gettext \
        --with-mhash \
        --with-config-file-path="$PHP_INI_DIR" \
        --with-config-file-scan-dir="$PHP_INI_DIR/conf.d" \
        --disable-cgi \
        --with-libxml-dir=/usr \
        --with-libedit \
        --with-fpm-user=www-data \
        --with-fpm-group=www-data \
        --with-kerberos \
        --enable-opcache \
        --enable-fpm \
    && make -j "$(getconf _NPROCESSORS_ONLN)" \
    && make install \
    && { find /usr/local/bin /usr/local/sbin -type f -perm +0111 -exec strip --strip-all '{}' + || true; } \
    && make clean \
    && cp /usr/local/etc/php-fpm.d/www.conf.default /usr/local/etc/php-fpm.d/www.conf \
    && mkdir /run/php && mkdir /run/nginx \
    # Remove dependencies
    && rm -rf /usr/src/* \
    && apk del .build-deps \
    # Composer
    && php -r "readfile('http://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer \
    && ln -sf /dev/stdout /var/log/nginx/access.log \
    && ln -sf /dev/stderr /var/log/nginx/error.log

COPY alpine-nginx /

CMD ["/sbin/runit-wrapper"]
