FROM debian:jessie-slim

# Custom helper scripts to download PHP and manage PHP extensions
COPY download-php install-php-ext /usr/local/bin/
COPY nginx/etc/apt/preferences.d/backports /etc/apt/preferences.d/backports

ENV PHP_INI_DIR /usr/local/etc/php
ENV PHP_CFLAGS="-fstack-protector-strong -fpic -fpie -O2"
ENV PHP_CPPFLAGS="$PHP_CFLAGS"
ENV PHP_LDFLAGS="-Wl,-O1 -Wl,--hash-style=both -pie"

# Persistent runtime dependencies
ENV PHP_DEPS \
        libedit2 \
        libicu52 \
        libxslt1.1 \
        libjpeg62-turbo \
        libfreetype6 \
        libxml2 \
        xz-utils \
        runit

# PHP build dependencies which get removed
ENV BUILD_DEPS \
        build-essential \
        autoconf \
        automake \
        libtool \
        bison \
        re2c \
        pkg-config \
        libc-dev \
        libedit-dev \
        libcurl4-openssl-dev \
        libfreetype6-dev \
        libgd-dev \
        libbz2-dev \
        libfcgi-dev \
        libfcgi0ldbl \
        libkrb5-dev \
        libpq-dev \
        libicu-dev \
        libpcre3-dev \
        libexpat1-dev \
        zlib1g-dev \
        libpng-dev \
        libxslt1-dev \
        libxml2-dev

RUN apt-get update && apt-get -y install curl ca-certificates --no-install-recommends \
    && echo 'deb http://ftp.debian.org/debian jessie-backports main' >> /etc/apt/sources.list \
    && echo 'deb http://packages.dotdeb.org jessie all' | tee --append /etc/apt/sources.list \
    && echo 'deb-src http://packages.dotdeb.org jessie all' | tee --append /etc/apt/sources.list \
    && echo 'deb http://packages.dotdeb.org jessie-nginx-http2 all' | tee --append /etc/apt/sources.list \
    && echo 'deb-src http://packages.dotdeb.org jessie-nginx-http2 all' | tee --append /etc/apt/sources.list \
    && curl https://www.dotdeb.org/dotdeb.gpg | apt-key add - \
    && apt-get update \
    && apt-get -y install openssl libssl-dev nginx --no-install-recommends \
    # PHP
    && mkdir -p $PHP_INI_DIR/conf.d \
    && apt-get install -y $PHP_DEPS $BUILD_DEPS --no-install-recommends \
    && cd /usr/src \
    && download-php \
    && cd php-* \
    && export CFLAGS="$PHP_CFLAGS" \
              CPPFLAGS="$PHP_CPPFLAGS" \
              LDFLAGS="$PHP_LDFLAGS" \
    && ./configure \
        # Core configure options
        --with-libdir=/lib/x86_64-linux-gnu \
        --disable-rpath \
        # Bundled PHP extensions
        --enable-bcmath \
        --enable-calendar \
        --enable-mbstring \
        --enable-exif \
        --enable-ftp \
        --with-gd \
        --enable-gd-native-ttf \
        --with-jpeg-dir=/usr \
        --with-png-dir=/usr \
        --with-freetype-dir \
        --enable-intl \
        --with-pcre-regex \
        --enable-mysqlnd \
        --with-openssl \
        --with-xsl \
        --enable-zip \
        --enable-sysvsem \
        --enable-sysvshm \
        --enable-sysvmsg \
        --enable-shmop \
        --enable-sockets \
        --with-zlib \
        --with-zlib-dir \
        --with-bz2 \
        --with-curl \
        --with-gettext \
        --with-mhash \
        --with-config-file-path="$PHP_INI_DIR" \
        --with-config-file-scan-dir="$PHP_INI_DIR/conf.d" \
        --disable-cgi \
        --with-libxml-dir=/usr \
        --with-libedit \
        --with-fpm-user=www-data \
        --with-fpm-group=www-data \
        --with-kerberos \
        --enable-opcache \
        --enable-fpm \
    && make -j "$(nproc)" \
    && make install \
    && { find /usr/local/bin /usr/local/sbin -type f -executable -exec strip --strip-all '{}' + || true; } \
    && make clean \
    && cp /usr/local/etc/php-fpm.d/www.conf.default /usr/local/etc/php-fpm.d/www.conf \
    && mkdir /run/php \
    # Remove dependencies
    && apt-get purge -y --auto-remove $BUILD_DEPS \
    && apt-get -y autoremove \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/src/* \
    && ln -sf /dev/stdout /var/log/nginx/access.log \
    && ln -sf /dev/stderr /var/log/nginx/error.log

COPY nginx /

CMD ["/sbin/runit-wrapper"]
