#!/bin/bash

# PHP version can be passed as an argument for example ./download-php 7.1.0
PHP_VERSION="${1:-7.1.4}"
GPG_KEY_1="A917B1ECDA84AEC2B568FED6F50ABC807BD5DCD0"
GPG_KEY_2="528995BFEDFBA7191D46839EF9BA0ADA31CBD89E"
PHP_URL="https://secure.php.net/get/php-$PHP_VERSION.tar.xz/from/this/mirror"
PHP_ASC_URL="https://secure.php.net/get/php-$PHP_VERSION.tar.xz.asc/from/this/mirror"
PHP_SHA256="71514386adf3e963df087c2044a0b3747900b8b1fc8da3a99f0a0ae9180d300b"
PHP_MD5="a74c13f8779349872b365e6732e8c98e"

curl -o php.tar.xz -OL $PHP_URL

if [ -n "$PHP_SHA256" ]; then
  echo "$PHP_SHA256 *php.tar.xz" | sha256sum -c -
fi;

if [ -n "$PHP_MD5" ]; then
  echo "$PHP_MD5 *php.tar.xz" | md5sum -c -
fi;

if [ -n "$PHP_ASC_URL" ]; then
  curl -o php.tar.xz.asc -OL "$PHP_ASC_URL"
  export GNUPGHOME="$(mktemp -d)"

  for key in $GPG_KEY_1 $GPG_KEY_2; do
    gpg --keyserver ha.pool.sks-keyservers.net --recv-keys $key
    gpg --fingerprint $key
  done;

  gpg --batch --verify php.tar.xz{.asc*,}
  rm -r "$GNUPGHOME"
fi;

tar -Jxf php.tar.xz
rm php.tar.xz php.tar.xz.asc
