#!/bin/bash

docker build -t phpearth/test:7.0-cli -f ../../docker/Dockerfile-7.0-cli ../../docker || exit 1
docker build -t phpearth/test:7.0-phpunit -f Dockerfile .

i=0
time dgoss run -it phpearth/test:7.0-phpunit || ((i++))

exit $i
