#!/bin/bash

docker build --no-cache -t phpearth/test:7.1 -f ../../docker/Dockerfile-7.1 ../../docker || exit 1
docker build --no-cache -t phpearth/test:7.1-iconv -f Dockerfile .

i=0
time dgoss run -it phpearth/test:7.1-iconv || ((i++))

exit $i
