#!/bin/bash

docker build --no-cache -t phpearth/test:7.3-cli -f ../../docker/7.3-cli.Dockerfile ../../docker || exit 1
docker build --no-cache -t phpearth/test:7.3-argon -f Dockerfile .

i=0
time dgoss run -it phpearth/test:7.3-argon || ((i++))

exit $i
