#!/bin/bash

docker build -t phpearth/test:7.0-cli -f ../../docker/7.0-cli.Dockerfile ../../docker || exit 1
docker build -t phpearth/test:7.0-composer -f Dockerfile .

i=0
time dgoss run -it phpearth/test:7.0-composer || ((i++))

exit $i
