#!/bin/bash

docker build -t phpearth/test:7.2 -f ../../docker/Dockerfile-7.2 ../../docker || exit 1
docker build -t phpearth/test:7.2-composer -f Dockerfile .

i=0
time dgoss run -it phpearth/test:7.2-composer || ((i++))

exit $i
