#!/bin/bash

docker build --no-cache -t phpearth/test:7.2-cli -f ../../docker/7.2-cli.Dockerfile ../../docker || exit 1
docker build --no-cache -t phpearth/test:7.2-argon -f Dockerfile .

i=0
time dgoss run -it phpearth/test:7.2-argon || ((i++))

exit $i
