#!/bin/bash

docker build -t phpearth/test:7.1-cli -f ../../docker/Dockerfile-7.1-cli ../../docker || exit 1
docker build -t phpearth/test:7.1-extensions -f Dockerfile .

i=0
time dgoss run -it phpearth/test:7.1-extensions || ((i++))

exit $i
