#!/bin/bash

docker build -t phpearth/test:7.2-cli -f ../../docker/7.2-cli.Dockerfile ../../docker || exit 1
docker build -t phpearth/test:7.2-extensions -f Dockerfile .

i=0
time dgoss run -it phpearth/test:7.2-extensions || ((i++))

exit $i
