FROM phpearth/php:7.1

RUN apk add --no-cache \
    php7.1-apcu \
    php7.1-imagick \
    php7.1-sodium \
    php7.1-memcached \
    php7.1-mongodb \
    php7.1-redis \
    php7.1-swoole \
    php7.1-xdebug
