FROM phpearth/php:7.1

RUN apk add --no-cache \
    php71-apcu \
    php71-imagick \
    php71-libsodium \
    php71-memcached \
    php71-mongodb \
    php71-redis \
    php71-swoole \
    php71-xdebug
